# Write your MySQL query statement below

SELECT E1.EMPLOYEE_ID FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID WHERE E1.MANAGER_ID IS NOT NULL AND E2.EMPLOYEE_ID IS NULL AND E1.SALARY < 30000 ORDER BY E1.EMPLOYEE_ID;
