# Write your MySQL query statement below
SELECT PRODUCT_ID, CASE WHEN N/D IS NULL THEN 0 ELSE ROUND(N/D, 2) END  AVERAGE_PRICE FROM (SELECT PRODUCT_ID, SUM(T_PRICE) N, SUM(UNITS) D FROM (SELECT P.PRODUCT_ID, P.PRICE*COALESCE(U.UNITS) T_PRICE, U.UNITS FROM PRICES P LEFT JOIN UNITSSOLD U ON U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE AND U.PRODUCT_ID = P.PRODUCT_ID) SUB GROUP BY PRODUCT_ID) SUB1;

#SELECT PRODUCT_ID, SUM(T_PRICE) N, SUM(UNITS) D FROM (SELECT P.PRODUCT_ID, P.PRICE*COALESCE(U.UNITS) T_PRICE, U.UNITS FROM PRICES P LEFT JOIN UNITSSOLD U ON U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE) SUB GROUP BY PRODUCT_ID;

