# Write your MySQL query statement below
#SELECT S.STUDENT_ID, S.STUDENT_NAME, E.SUBJECT_NAME, COUNT(*) attended_exams FROM STUDENTS S LEFT JOIN EXAMINATIONS E ON S.STUDENT_ID = E.STUDENT_ID GROUP BY S.STUDENT_ID, S.STUDENT_NAME, E.SUBJECT_NAME;

#SELECT * FROM SUBJECTS S LEFT JOIN (SELECT S.STUDENT_ID, S.STUDENT_NAME, E.SUBJECT_NAME FROM STUDENTS S INNER JOIN EXAMINATIONS E ON S.STUDENT_ID = E.STUDENT_ID) SUB ON S.SUBJECT_NAME = SUB.SUBJECT_NAME;

#(SELECT S.STUDENT_ID, S.STUDENT_NAME, E.SUBJECT_NAME FROM STUDENTS S INNER JOIN EXAMINATIONS E ON S.STUDENT_ID = E.STUDENT_ID)

#SELECT * FROM STUDENTS CROSS JOIN SUBJECTS

/*
SELECT SUB.STUDENT_ID, SUB.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(CASE WHEN E.STUDENT_ID IS NULL THEN 0 END) attended_exams
FROM 
(SELECT * FROM STUDENTS CROSS JOIN SUBJECTS) SUB LEFT JOIN 
EXAMINATIONS E ON SUB.STUDENT_ID = E.STUDENT_ID AND SUB.SUBJECT_NAME = E.SUBJECT_NAME GROUP BY SUB.STUDENT_ID, SUB.STUDENT_NAME, SUB.SUBJECT_NAME ORDER BY SUB.STUDENT_ID ASC,  SUB.SUBJECT_NAME ASC;
*/

SELECT SUB.STUDENT_ID, SUB.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.STUDENT_ID) attended_exams
FROM 
(SELECT * FROM STUDENTS CROSS JOIN SUBJECTS) SUB LEFT JOIN 
EXAMINATIONS E ON SUB.STUDENT_ID = E.STUDENT_ID AND SUB.SUBJECT_NAME = E.SUBJECT_NAME GROUP BY SUB.STUDENT_ID, SUB.STUDENT_NAME, SUB.SUBJECT_NAME ORDER BY SUB.STUDENT_ID ASC,  SUB.SUBJECT_NAME ASC;